variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "4"
  ORD_SOUMET_TMPFS: "1G"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_W: "30"
  GIT_SUBMODULE_STRATEGY: none
  BUILD_BASE_BASE_DIR: /home/sici000/special_builds
  BUILD_BASE_DIR: /home/sici000/special_builds/precaution
  PIPELINE_SUBDIR: /home/sici000/special_builds/precaution/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}

stages:
  - build
  - run_intel
  - run_gnu
  - package
  - deploy

before_script:
  - export CLICOLOR_FORCE=1
  - source ~/ci-admin/env/init.sh

#----- rhel-8-amd64_gnu-9.3.0
build:rhel-8-amd64_gnu-9.3.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - git submodule update --recursive --init
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-9.3.0
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-amd64-64-gnu-9.3.0
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-amd64-64-gnu-9.3.0 .
    - ./scripts/link-dbase.sh
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-9.3.0
    - cmake -DWITH_SYSTEM_RPN=FALSE ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-amd64-64-gnu-9.3.0
    - sps_dbase

#----- rhel-8-amd64_gnu-12.1.0
build:rhel-8-amd64_gnu-12.1.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - git submodule update --recursive --init
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-12.1.0
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-amd64-64-gnu-12.1.0
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-amd64-64-gnu-12.1.0 .
    - ./scripts/link-dbase.sh
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-12.1.0
    - cmake -DWITH_SYSTEM_RPN=FALSE ${SRC_DIR}
    - time make -j $NCPUS
    - time make -j work
  allow_failure: true
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-amd64-64-gnu-12.1.0
    - sps_dbase

#----- rhel-8-icelake-64-intel-2022.1.2
# U2 Intel 2022 with RPN-SI sources
build:intel-with-sources-rhel-8-icelake-64-intel-2022.1.2:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - set -e
    - . ./.eccc_setup_intel
    - git submodule update --recursive --init
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2-with-sources
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2-with-sources
    - cmake -DWITH_SYSTEM_RPN=FALSE ${SRC_DIR}
    - time make -j $NCPUS
  allow_failure: true

# U2 Intel 2022 with installed RPN-SI libs
# Used for testing configs and for SSM package
build:rhel-8-icelake-64-intel-2022.1.2:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - set -e
    - . ./.eccc_setup_intel
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2022.1.2
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2022.1.2 .
    - ./scripts/link-dbase.sh
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-icelake-64-intel-2022.1.2
    - sps_dbase

package:rhel-8-icelake-64-intel-2022.1.2:
   variables:
      ORD_SOUMET_CPUS: "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - tags
      - dev
      - schedules
   dependencies:
      - build:rhel-8-icelake-64-intel-2022.1.2
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . ./.eccc_setup_intel
      - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

# U2 Intel 2021 with installed RPN-SI libs
# Used for SSM package
build:rhel-8-icelake-64-intel-2021.4.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
  - concurrent
  only:
  - tags
  - dev
  - schedules
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - set -e
    - . ./.eccc_setup_intel_2021.4.0
    - SRC_DIR=$(pwd)
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2021.4.0
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2021.4.0
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS

package:rhel-8-icelake-64-intel-2021.4.0:
   variables:
      ORD_SOUMET_CPUS: "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - tags
      - dev
      - schedules
   dependencies:
      - build:rhel-8-icelake-64-intel-2021.4.0
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . ./.eccc_setup_intel_2021.4.0
      - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2021.4.0
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-18.04-amd64_inteloneapi-2021.4.0
build:ubuntu-18.04-amd64-intel-2021.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-18.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS: "4"
      ORD_SOUMET_W: "30"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: build
   tags:
     - concurrent
   only:
     - dev
     - tags
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2021.4.0
      - SRC_DIR=$(pwd)
      - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-18.04-amd64-64-intel-2021.4.0
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-18.04-amd64-64-intel-2021.4.0
      - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
      - time make -j $NCPUS

package:ubuntu-18.04-amd64-intel-2021.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-18.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-18.04-amd64-intel-2021.4.0
   environment:
      name: testing
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2021.4.0
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-18.04-amd64-64-intel-2021.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-18.04-amd64_inteloneapi-2022.1.2
build:ubuntu-18.04-amd64-intel-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-18.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS: "4"
      ORD_SOUMET_W: "30"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: build
   tags:
     - concurrent
   only:
     - dev
     - tags
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel
      - SRC_DIR=$(pwd)
      - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-18.04-amd64-64-intel-2022.1.2
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-18.04-amd64-64-intel-2022.1.2
      - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
      - time make -j $NCPUS

package:ubuntu-18.04-amd64-intel-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-18.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-18.04-amd64-intel-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-18.04-amd64-64-intel-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_inteloneapi-2022.1.2
build:ubuntu-22.04-amd64-intel-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-22.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: build
   tags:
     - concurrent
   only:
     - dev
     - tags
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel
      - SRC_DIR=$(pwd)
      - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2022.1.2
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2022.1.2
      - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
      - time make -j $NCPUS

package:ubuntu-22.04-amd64-intel-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-22.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64-intel-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - set -e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

deploy:staging:
   stage: deploy
   tags:
      - concurrent
   only:
      - tags
      - dev
      - schedules
   script:
      - ~/ci-admin/bin/ci-stage-ssm.sh gem gem "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

#----- Running test configuration for rhel-8-icelake-64-intel-2022.1.2
SPS_cfgs_intel:
  stage: run_intel
  tags:
    - U2
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/SPS_cfgs --ptopo 2x2x1 --inorder

#----- Running test configuration for rhel-8-amd64_gnu-9.3.0
SPS_cfgs_gnu_9.3.0:
  stage: run_gnu
  tags:
    - U2
  dependencies:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  only:
  - dev
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/SPS_cfgs --ptopo 2x2x1 --inorder
